---
title: "Homework 7"
author: "Ameth FAYE"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## RENDU

```{r}
library(haven)
cereales <- read_dta("C:/Users/HP/Desktop/ISEP2CoursR2024/Base/cereales.dta")
library(readxl)
conversion <- read_excel("C:/Users/HP/Desktop/ISEP2CoursR2024/Base/Table de conversion phase 2.xlsx")

library(tidyverse)
glimpse(cereales)
View(cereales)

colnames(cereales)[4:14] <- c("AutresCereales","Qtty_cons",
                              "Unite_cons","Taille_cons",
                              "AutoCons","AutresProv",
                              "DernierAchat","Qtty_achat",
                              "Unite_achat","Taille_achat",
                              "Value_achat")
rownames(cereales$cereales__id)
summary(cereales)


##Gestion des NA

##Suppression des ménages ne consommant pas de céréales
attach(cereales)
anyNA(Qtty_cons)

##Création d'une variable temporaire
cereales$t <- ifelse(is.na(Qtty_cons)==1,1,0)
table(cereales$t)
cereales_na <- cereales[cereales$t==1,] ##Sous la base cereales
View(cereales_na)

##Suppression des ménages n'ayant pas déclaré les qtités cons

cereales <- cereales[cereales$t==0,]
dim(cereales)

##Suppression de la variable temporaire
cereales$t <- NULL


# Renomer, créer, labeliser les variables,  Recoder ;


labprod <- c("Riz local brisé"	,"Riz local entier"	,"Riz importé brisé" ,"Riz importé entier"	,"Riz importé 3"	,"Maïs en épi","Maïs en grain"	,"Mil"	,"Sorgho"	,"Blé"	,"Fonio"	,"Autres céréales"	,"Farine de maïs"	,"semoule de mais"	,"Farine/semoule de mil"	,"semoule de mil"	,"Farine de blé local ou importé"	,"semoule de blé "	,"Autres farines de céréales"	,"Autres semoules de céréales"	,"Pâtes alimentaires"	,"Pain moderne"	,"Pain moderne type 2"	,"Pain traditionnel"	,"Pains traditionnel type 2"	,"Céréales de petit déjeuner" ,"Croissants"	,"Biscuits"	,"Gâteaux"	,"Beignets, galettes")
levprod <- unique(cereales$cereales__id)
edit(levprod)
levprodN <- names(attr(cereales$cereales__id,"labels"))
levprodL <- unname(attr(cereales$cereales__id,"labels"))

cereales$produit1 <- as.factor(cereales$cereales__id)
glimpse(cereales)
table(cereales$produit1)
cereales$produit <- factor(cereales$cereales__id, 
                           levels = levprodL,
                           labels = levprodN )
table(cereales$produit)

glimpse(cereales)
edit(cereales$Unite_cons)
cereales$unite_cons <- factor(cereales$Unite_cons,
                              levels = unname(attr(cereales$Unite_cons,
                                                   "labels")),
                              labels =names(attr(cereales$Unite_cons,
                                                 "labels")))
cereales$taille_cons <- factor(cereales$Taille_cons,
                               levels = unname(attr(cereales$Taille_cons,
                                                    "labels")),
                               labels =names(attr(cereales$Taille_cons,
                                                  "labels")))
# 5 changer de type ;
# 6 d´ecoupage en classe ;identifier une cereale et une unite standard;


cereales$classCereal <- cut(cereales$Qtty_cons, 
                            labels = c("Tres faible",
                                       "Faible",
                                       "Moyen",
                                       "Eleve"),
                            breaks = c(0,50,70,110,168))

table(cereales$classCereal)
cereales$classCereal_RizKg <- ifelse(cereales$cereales__id==1 & cereales$Unite_cons==100, 
                                     cut(cereales$Qtty_cons, 
                                         labels = c("Tres faible",
                                                    "Faible",
                                                    "Moyen",
                                                    "Eleve"),
                                         breaks = c(0,50,70,110,168)),NA)
table(cereales$classCereal_RizKg)

c0 <- unique(cereales[cereales$Unite_cons==100,"Taille_cons"])
c1 <- cereales[cereales$cereales__id<5 & cereales$unite_cons==100, ]

#Fusionnons les bases conversion et cereales suivants les clefs produits, untité_cons et Taille_cons
#Création des clefs produit,unite_cons et taille_cons dans la base conversion  
conversion$produit <- factor(conversion$produitID, 
                             levels = conversion$produitID,
                             labels = conversion$produitNom )
conversion$unite_cons <- factor(conversion$uniteID,
                                conversion$uniteID,
                                labels =conversion$uniteNom)
conversion$taille_cons <- factor(conversion$tailleID,
                                 levels = conversion$tailleID,
                                 labels = conversion$tailleNom)
fusion <- merge(cereales, conversion, by = c("produit", "unite_cons", "taille_cons"),allx=TRUE)

```


